# Generated by Django 5.0.6 on 2026-10-10 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Shoe Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model_number', models.CharField(max_length=150, unique=True)),
                ('material', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNISEX', 'Unisex'), ('CHILDREN', 'Children')], default='UNISEX', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shoes/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoes', to='Category.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shoes', to='shoes.shoecompany')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShoeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional price ovveride for this size', max_digits=10, null=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shoes.shoe')),
            ],
            options={
                'ordering': ['shoe', 'size'],
            },
        ),
        migrations.AddIndex(
            model_name='shoe',
            index=models.Index(fields=['name'], name='shoes_shoe_name_b6cab0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shoevariant',
            unique_together={('shoe', 'size')},
        ),
    ]
